'''
Author: error: error: git config user.name & please set dead value or install git && error: git config user.email & please set dead value or install git & please set dead value or install git
Date: 2024-04-03 11:48:47
LastEditors: error: error: git config user.name & please set dead value or install git && error: git config user.email & please set dead value or install git & please set dead value or install git
LastEditTime: 2024-04-25 17:52:38
FilePath: /zhangdi/mycode/paper1/models/IBOTvit.py
Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
'''
#from .encoders import vit_base
from torchvision import transforms
import torch 
#from .core import Extractor
#from ...constants import IMAGENET_MEAN, IMAGENET_STD, MODEL_WEIGHTS
from typing import Callable, Dict, List, Optional, Tuple
from loguru import logger
from torch import nn
from functools import partial
import math
import warnings
import numpy as np
from abc import abstractmethod
from PIL.Image import Image
import os

TILE_SIZES = {
    "iBOTViTBasePANCAN": 224,
}
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)
class Extractor(nn.Module):
    """Base Extractor class."""

    @property
    def transform(self) -> Callable[[Image], torch.Tensor]:
        """
        Transform method to apply element wise.
        Default is identity.

        Returns
        -------
        transform: Callable[[Image], torch.Tensor]
        """
        return lambda x: x

    @abstractmethod
    def __call__(self, images: torch.Tensor) -> torch.Tensor:
        """Returns final features.

        Parameters
        ----------
        images: torch.Tensor
            (BS, C, H, W)

        Returns
        -------
        features : torch.Tensor
            (BS, D)
        """
        raise NotImplementedError

    def extract_feature_maps(
        self, images: torch.Tensor
    ) -> Dict[str, torch.Tensor]:
        """Returns a dictionary with intermediate features.

        Parameters
        ----------
        images: torch.Tensor
            (BS, C, H, W)

        Returns
        -------
        features : Dict[str, torch.Tensor]
            example shapes: {
                "layer4": (BS, 256, 56, 56),
                "layer5": (BS, 512, 28, 28),
                "layer6": (BS, 1024, 14, 14),
                "layer7": (BS, 2048, 7, 7),
            }
        """
        raise NotImplementedError

    def extract_features_as_numpy(self, images: torch.Tensor) -> np.ndarray:
        """Returns features as a numpy array.

        Parameters
        ----------
        images: torch.Tensor
            (BS, C, H, W)

        Returns
        -------
        features: np.ndarray
            (BS, D)
        """
        features = self.__call__(images)
        return features.cpu().detach().numpy()
def _no_grad_trunc_normal_(
    tensor: torch.Tensor, mean: float, std: float, a: float, b: float
) -> torch.Tensor:
    """Truncated normal initialization."""

    def _norm_cdf(x: float) -> float:
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values.
        lb = _norm_cdf((a - mean) / std)
        ub = _norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * lb - 1, 2 * ub - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal.
        tensor.erfinv_()

        # Transform to proper mean, std.
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range.
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(
    tensor: torch.Tensor,
    mean: float = 0.0,
    std: float = 1.0,
    a: float = -2.0,
    b: float = 2.0,
) -> torch.Tensor:
    r"""Truncated normal initialization.

    Fills the input tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    Parameters
    ----------
    tensor : torch.Tensor
        Input tensor (to be initialized).

    mean : float = 0
        Mean of the Normal distribution.

    std : float = 1
        Standard deviation of the Normal distribution.

    a : float = 2
        The minimum cutoff value.

    b : float = 2
        The maximum cutoff value.

    Returns
    -------
    torch.Tensor
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)
class DropPath(nn.Module):
    """``torch.nn`` module for Drop path implementation. See [1]_ for details.

    References
    ----------
    .. [1] https://github.com/huggingface/pytorch-image-models/blob/main/timm/layers/drop.py#L157
    """

    def __init__(self, drop_prob: Optional[float] = None) -> None:
        """Initialize the DropPath class.

        Parameters
        ----------
        drop_prob : float
            The probability of dropping each element, by default None.
        """
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Apply drop path to an input tensor.

        Parameters
        ----------
        x : torch.Tensor
            The input tensor.

        Returns
        -------
        torch.Tensor
            Input tensor with dropout applied on a given path.
        """
        return drop_path(x, self.drop_prob, self.training)
def drop_path(
    x: torch.Tensor,
    drop_prob: float = 0.0,
    training: bool = False,
) -> torch.Tensor:
    """Drop paths (Stochastic Depth) per sample (when applied in main path of
    residual blocks). See [1]_ for details.

    Parameters
    ----------
    x : torch.Tensor
        The input tensor.
    drop_prob : float = 0.0
        The probability of dropping a path.
    training : bool = False
        Whether the model is in training mode or not.

    Returns
    -------
    torch.Tensor
        The output array after applying drop path.

    References
    ----------
    .. [1] https://github.com/huggingface/pytorch-image-models/blob/main/timm/layers/drop.py#L137
    """
    if drop_prob == 0.0 or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (
        x.ndim - 1
    )  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(
        shape, dtype=x.dtype, device=x.device
    )
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output

class Mlp(nn.Module):
    """MLP as used in Vision Transformer. See [1]_ for details.

    Parameters
    ----------
    in_features : int
        Input feature size.
    hidden_features : int = None
        Hidden feature size, by default None (uses input feature size).
    out_features : int = None
        Output feature size, by default None (uses input feature size).
    act_layer : nn.Module = nn.GELU
        Activation layer, by default nn.GELU.
    drop : float = 0.0
        Dropout rate, by default 0.0.

    Attributes
    ----------
    fc1 : nn.Linear
        First fully connected layer.
    act : nn.Module
        Activation layer.
    fc2 : nn.Linear
        Second fully connected layer.
    drop : nn.Dropout
        Dropout layer.

    References
    ----------
    .. [1] https://github.com/huggingface/pytorch-image-models/blob/main/timm/layers/mlp.py#L13

    """

    def __init__(
        self,
        in_features: int,
        hidden_features: Optional[int] = None,
        out_features: Optional[int] = None,
        act_layer: nn.Module = nn.GELU,
        drop: float = 0.0,
    ) -> None:
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass of the MLP.

        Parameters
        ----------
        x : torch.Tensor
            Input tensor.

        Returns
        -------
        torch.Tensor
            Output tensor.
        """
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    """Attention module for Vision Transformer as implemented in [1]_.

    Parameters
    ----------
    dim : int
        Input dimension.
    num_heads : int = 8
        Number of attention heads, by default 8.
    qkv_bias : bool = False
        Whether to include biases in the linear transformations of q, k, and v,
        by default False.
    qk_scale : float = None
        Scale factor for qk dot product, by default None.
    attn_drop : float = 0.0
        Dropout rate for attention weights, by default 0.0.
    proj_drop : float = 0.0
        Dropout rate for output tensor, by default 0.0.

    Attributes
    ----------
    num_heads : int
        Number of attention heads.
    scale : float
        Scale factor for qk dot product.
    qkv : nn.Linear
        Linear transformation for q, k, and v.
    attn_drop : nn.Dropout
        Dropout layer for attention weights.
    proj : nn.Linear
        Linear transformation for output tensor.
    proj_drop : nn.Dropout
        Dropout layer for output tensor.

    References
    ----------
    .. [1] https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/vision_transformer.py
    """

    def __init__(
        self,
        dim: int,
        num_heads: int = 8,
        qkv_bias: bool = False,
        qk_scale: Optional[float] = None,
        attn_drop: float = 0.0,
        proj_drop: float = 0.0,
    ):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim**-0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """Forward pass of the attention module.

        Parameters
        ----------
        x : torch.Tensor
            Input tensor.

        Returns
        -------
        Tuple[torch.Tensor, torch.Tensor]
            Output tensor.
        """
        B, N, C = x.shape
        qkv = (
            self.qkv(x)
            .reshape(B, N, 3, self.num_heads, C // self.num_heads)
            .permute(2, 0, 3, 1, 4)
        )
        q, k, v = qkv[0], qkv[1], qkv[2]

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x, attn

class Block(nn.Module):
    """Vision Transformer Block as implemented in [1]_.

    Parameters
    ----------
    dim : int
        The dimension of the input.
    num_heads : int
        The number of attention heads.
    mlp_ratio : float = 4.0
        The ratio of hidden dimension to input dimension in the MLP, by default 4.0.
    qkv_bias : bool = False
        Whether to include biases in the query, key, and value projections, by default False.
    qk_scale : float = None
        The scaling factor for query-key dot product, by default None.
    drop : float = 0.0
        The dropout probability, by default 0.0.
    attn_drop : float = 0.0
        The dropout probability for attention weights, by default 0.0.
    drop_path : float = 0.0
        The dropout probability for the residual connection, by default 0.0.
    act_layer : torch.nn.Module = torch.nn.GELU
        The activation layer used in the MLP, by default ``torch.nn.GELU``.
    norm_layer : torch.nn.Module = torch.nn.LayerNorm
        The normalization layer, by default ``torch.nn.LayerNorm``.
    init_values : int
        The initial values for gamma_1 and gamma_2, by default 0.

    Attributes
    ----------
    norm1 : torch.nn.Module
        The normalization layer before the attention module.
    attn : Attention
        The attention module.
    drop_path : Union[DropPath, nn.Identity]
        The dropout layer for the residual connection.
    norm2 : torch.nn.Module
        The normalization layer after the MLP.
    mlp : Mlp
        The MLP module.
    gamma_1 : Optional[torch.nn.Parameter]
        The learnable parameter gamma_1.
    gamma_2 : Optional[torch.nn.Parameter]
        The learnable parameter gamma_2.

    References
    ----------
    .. [1] https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/vision_transformer.py
    """

    def __init__(
        self,
        dim: int,
        num_heads: int,
        mlp_ratio: float = 4.0,
        qkv_bias: bool = False,
        qk_scale: Optional[float] = None,
        drop: float = 0.0,
        attn_drop: float = 0.0,
        drop_path: float = 0.0,  # pylint: disable=redefined-outer-name
        act_layer: nn.Module = nn.GELU,
        norm_layer: nn.Module = nn.LayerNorm,
        init_values: int = 0,
    ) -> None:
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim,
            num_heads=num_heads,
            qkv_bias=qkv_bias,
            qk_scale=qk_scale,
            attn_drop=attn_drop,
            proj_drop=drop,
        )
        self.drop_path = (
            DropPath(drop_path) if drop_path > 0.0 else nn.Identity()
        )
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            act_layer=act_layer,
            drop=drop,
        )

        if init_values > 0:
            self.gamma_1 = nn.Parameter(
                init_values * torch.ones((dim)), requires_grad=True
            )
            self.gamma_2 = nn.Parameter(
                init_values * torch.ones((dim)), requires_grad=True
            )
        else:
            self.gamma_1, self.gamma_2 = None, None

    def forward(
        self, x: torch.Tensor, return_attention: bool = False
    ) -> torch.Tensor:
        """
        Forward pass of the Vision Transformer Block module.

        Parameters
        ----------
        x : torch.Tensor
            The input tensor.
        return_attention : bool
            Whether to return the attention weights, by default False.

        Returns
        -------
        torch.Tensor
            The output tensor.
        """
        y, attn = self.attn(self.norm1(x))
        if return_attention:
            return attn
        if self.gamma_1 is None:
            x = x + self.drop_path(y)
            x = x + self.drop_path(self.mlp(self.norm2(x)))
        else:
            x = x + self.drop_path(self.gamma_1 * y)
            x = x + self.drop_path(self.gamma_2 * self.mlp(self.norm2(x)))
        return x
class VisionTransformer(nn.Module):
    """Vision Transformer in PyTorch as implemented in [1]_.

    Parameters
    ----------
    img_size : List[int] = [224]
        The size of the input image.
    patch_size : int = 16
        The size of each patch in the input image.
    in_chans : int = 3
        The number of input channels.
    num_classes : int = 0
        The number of output classes.
    embed_dim : int = 768
        The dimension of the token embeddings.
    depth : int = 12
        The number of transformer blocks.
    num_heads : int = 12
        The number of attention heads.
    mlp_ratio : float = 4.0
        The ratio of the hidden dimension to the input dimension in the feed-forward network.
    qkv_bias : bool = False
        Whether to include biases to the query, key, and value linear layers.
    qk_scale : Optional[float] = None
        The scale factor for query and key.
    drop_rate : float = 0.0
        The dropout rate.
    attn_drop_rate : float = 0.0
        The dropout rate for attention probabilities.
    drop_path_rate : float = 0.0
        The dropout rate for residual connections.
    norm_layer : Callable = partial(torch.nn.LayerNorm, eps=1e-6)
        The normalization layer to be used.
    return_all_tokens : bool = False
        Whether to return all tokens or just the first token.
    init_values : int = 0
        The initial values for convolutional layers.
    use_mean_pooling : bool = False
        Whether to use mean pooling or not.
    masked_im_modeling : bool = False
        Whether to perform masked image modeling or not.

    References
    ----------
    .. [1] https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/vision_transformer.py
    """

    def __init__(
        self,
        img_size: List[int] = [224],
        patch_size: int = 16,
        in_chans: int = 3,
        num_classes: int = 0,
        embed_dim: int = 768,
        depth: int = 12,
        num_heads: int = 12,
        mlp_ratio: float = 4.0,
        qkv_bias: bool = False,
        qk_scale: Optional[float] = None,
        drop_rate: float = 0.0,
        attn_drop_rate: float = 0.0,
        drop_path_rate: float = 0.0,
        norm_layer: Callable = partial(nn.LayerNorm, eps=1e-6),
        return_all_tokens: bool = False,
        init_values: int = 0,
        use_mean_pooling: bool = False,
        masked_im_modeling: bool = False,
    ):
        super().__init__()
        self.num_features = self.embed_dim = embed_dim
        self.return_all_tokens = return_all_tokens

        self.patch_embed = PatchEmbed(
            img_size=img_size[0],
            patch_size=patch_size,
            in_chans=in_chans,
            embed_dim=embed_dim,
        )
        num_patches = self.patch_embed.num_patches

        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(
            torch.zeros(1, num_patches + 1, embed_dim)
        )
        self.pos_drop = nn.Dropout(p=drop_rate)

        # Stochastic depth decay rule.
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]
        self.blocks = nn.ModuleList(
            [
                Block(
                    dim=embed_dim,
                    num_heads=num_heads,
                    mlp_ratio=mlp_ratio,
                    qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate,
                    attn_drop=attn_drop_rate,
                    drop_path=dpr[i],
                    norm_layer=norm_layer,
                    init_values=init_values,
                )
                for i in range(depth)
            ]
        )

        self.norm = (
            nn.Identity() if use_mean_pooling else norm_layer(embed_dim)
        )
        self.fc_norm = norm_layer(embed_dim) if use_mean_pooling else None

        # Classifier head.
        self.head = (
            nn.Linear(embed_dim, num_classes)
            if num_classes > 0
            else nn.Identity()
        )
        
        trunc_normal_(self.pos_embed, std=0.02)
        trunc_normal_(self.cls_token, std=0.02)
        self.apply(self._init_weights)

        # Masked image modeling.
        self.masked_im_modeling = masked_im_modeling
        if masked_im_modeling:
            self.masked_embed = nn.Parameter(torch.zeros(1, embed_dim))
    def _init_weights(self, module):
        if isinstance(module, torch.nn.Linear):
            torch.nn.init.xavier_uniform_(module.weight)
    #自己加的
    def forward(self, x):
        x = self.prepare_tokens(x)
        for blk in self.blocks:
            x = blk(x)
        x = self.norm(x)
        x = self.head(x[:, 0])
        #(x[:, 0]:返回的是经过所有Transformer编码层处理并归一化后的[CLS]令牌的嵌入向量。在ViT模型中，这个[CLS]令牌的嵌入向量被视为整个图像的全局表示，常用于分类任务。
        #具体地说，这个向量可以被输入到一个或多个线性层（分类头）中，以预测图像的类别。
        return x
    def interpolate_pos_encoding(self, x, w, h):
        npatch = x.shape[1] - 1
        N = self.pos_embed.shape[1] - 1
        if npatch == N and w == h:
            return self.pos_embed
        class_pos_embed = self.pos_embed[:, 0]
        patch_pos_embed = self.pos_embed[:, 1:]
        dim = x.shape[-1]
        w0 = w // self.patch_embed.patch_size
        h0 = h // self.patch_embed.patch_size
        # we add a small number to avoid floating point error in the interpolation
        # see discussion at https://github.com/facebookresearch/dino/issues/8
        w0, h0 = w0 + 0.1, h0 + 0.1
        patch_pos_embed = nn.functional.interpolate(
            patch_pos_embed.reshape(1, int(math.sqrt(N)), int(math.sqrt(N)), dim).permute(0, 3, 1, 2),
            scale_factor=(w0 / math.sqrt(N), h0 / math.sqrt(N)),
            mode='bicubic',
        )
        assert int(w0) == patch_pos_embed.shape[-2] and int(h0) == patch_pos_embed.shape[-1]
        patch_pos_embed = patch_pos_embed.permute(0, 2, 3, 1).view(1, -1, dim)
        return torch.cat((class_pos_embed.unsqueeze(0), patch_pos_embed), dim=1)
    def prepare_tokens(self, x):
        B, nc, w, h = x.shape
        x = self.patch_embed(x)  # patch linear embedding

        # add the [CLS] token to the embed patch tokens
        cls_tokens = self.cls_token.expand(B, -1, -1)
        x = torch.cat((cls_tokens, x), dim=1)

        # add positional encoding to each token
        x = x + self.interpolate_pos_encoding(x, w, h)

        return self.pos_drop(x)
    
    def get_intermediate_layers(self, x, n=5):
        x = self.prepare_tokens(x)
        # we return the output tokens from the `n` last blocks
        output = []
        for i, blk in enumerate(self.blocks):
            x = blk(x)
            if n==1:#一个特征，则赋予最后一层特征
                if i ==len(self.blocks)-1:
                    output.append(self.norm(x))
            elif n==2:#两个特征，则赋予最后一层和第一层特征
                if i ==len(self.blocks)-1 or i == 0:
                    output.append(self.norm(x))
            elif n==3:#三个特征，则赋予最后一层、中间层和最后一层
                if i ==len(self.blocks)-1 or i == 0 or i ==1:
                    output.append(self.norm(x))
            elif n==5:
                if i in [0,1,5,len(self.blocks)-2,len(self.blocks)-1]:
                    output.append(self.norm(x))
            else:
                if len(self.blocks) - i <= n:
                    output.append(self.norm(x))
        return output
        #if module.bias is not None:
        #    torch.nn.init.constant_(module.bias, 0)
class PatchEmbed(nn.Module):
    """2D Image to Patch Embedding as implemented in [1]_.

    Parameters
    ----------
    img_size:  int = 224
        Size of the input image (both height and width), by default 224.
    patch_size: int = 16
        Size of each patch, by default 16.
    in_chans: int = 3
        Number of input channels, by default 3.
    embed_dim: int = 768
        Dimension of the embedded patch representation, by default 768.

    Attributes
    ----------
    img_size: int
        Size of the input image (both height and width).
    patch_size: int
        Size of each patch.
    num_patches: int
        Total number of patches in the image.
    proj: nn.Conv2d
        Convolutional layer used for projection.


    References
    ----------
    .. [1] https://github.com/huggingface/pytorch-image-models/blob/main/timm/layers/patch_embed.py#L25
    """

    def __init__(
        self,
        img_size: int = 224,
        patch_size: int = 16,
        in_chans: int = 3,
        embed_dim: int = 768,
    ) -> None:
        super().__init__()
        num_patches = (img_size // patch_size) * (img_size // patch_size)
        self.img_size = img_size
        self.patch_size = patch_size
        self.num_patches = num_patches

        self.proj = nn.Conv2d(
            in_chans, embed_dim, kernel_size=patch_size, stride=patch_size
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass of the PatchEmbed module.

        Parameters
        ----------
        x: torch.Tensor
            Input tensor of shape (``B``, ``C``, ``H``, ``W``) where ``B`` is the
            batch size, ``C`` is the number of channels, ``H`` is the input image
            height, and ``W`` is the input image width.

        Returns
        -------
        torch.Tensor
            Output tensor of shape (``B``, ``embed_dim``, ``num_patches``) where
            ``B`` is the batch size, ``embed_dim`` is the dimension of the embedded
            patch  representation, and ``num_patches`` is the total number of
            patches in the image.
        """
        #  B, C, H, W = x.shape
        return self.proj(x).flatten(2).transpose(1, 2)


def vit_base(patch_size: int = 16, **kwargs):
    """Create a Base Vision Transformer model (ViT-B).

    Parameters
    ----------
    patch_size : int = 16
        Size of the patches in the input image.
    **kwargs : keyword arguments
        Additional arguments to be passed to the VisionTransformer constructor.

    Returns
    -------
    model : VisionTransformer
        The Base Vision Transformer model.
    """
    model = VisionTransformer(
        patch_size=patch_size,
        embed_dim=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4,
        qkv_bias=True,
        **kwargs
    )
    return model


class iBOTViT(Extractor):  # pylint: disable=abstract-method
    """Vision transform model trained with iBOT (See [1]_).

    Parameters
    ----------
    architecture: str = 'vit_base_pancan'
        Model architecture. Must only be "vit_base_pancan" as of now.
    encoder: str = 'teacher'
        Whether to load the weights from the student or teacher encoder.
    mean: Tuple[float, float, float] = IMAGENET_MEAN
        Mean values used for mean/std normalization of image channels.
    std: Tuple[float, float, float] = IMAGENET_STD:
        Std values used for mean/std normalization of image channels.

    References
    ----------
    .. [1] Jinghao Zhou, Chen Wei, Huiyu Wang, Wei Shen, Cihang Xie, Alan Yuille, and Tao Kong.
    Image BERT pre-training with online tokenizer. In International Conference on Learning
    Representations, 2022
    """

    def __init__(
        self,
        architecture="vit_base_pancan",
        encoder="teacher",
        mean: Tuple[float, float, float] = IMAGENET_MEAN,
        std: Tuple[float, float, float] = IMAGENET_STD,
        weights_path: Optional[str] = None,
        path='/home/zhangdi/mycode/paper1/models/ibot_vit.pth'
    ):
        super(iBOTViT, self).__init__()

        self.mean = mean
        self.std = std
        self.encoder = encoder

        # Load weights for iBOT[ViT-B]PanCancer.
        assert (
            architecture == "vit_base_pancan"
        ), "Weights are released for `vit_base_pancan` architecture only."
        self.backbone = vit_base(
            patch_size=16, num_classes=2, use_mean_pooling=False
        )
        self._weights_path = weights_path
        if self._weights_path is None:
            self._weights_path = path

        # Load state_dict.
        state_dict = torch.load(self._weights_path, map_location="cpu")
        state_dict = state_dict[self.encoder]
        state_dict = {
            k.replace("module.", ""): v for k, v in state_dict.items()
        }
        state_dict = {
            k.replace("backbone.", ""): v for k, v in state_dict.items()
        }
        # Set weights with state_dict.
        msg = self.backbone.load_state_dict(state_dict, strict=False)
        #logger.info(
        #    f"Pretrained weights found at {self._weights_path} and loaded with msg: {msg}"
        #)

    @property
    def transform(self):
        """Transform method to apply element wise.

        Returns
        -------
        transform: Callable[[Input], Transformed]
        """
        transform_ops = [
            transforms.ToTensor(),
            transforms.Normalize(
                mean=self.mean,
                std=self.std,
            ),
        ]
        return transforms.Compose(transform_ops)
    

    def __call__(self, images: torch.Tensor,n:int,output:bool) -> torch.Tensor:
        """
        Compute and return features.

        Parameters
        ----------
        images: torch.Tensor
            input of size (n_tiles, n_channels, dim_x, dim_y)

        Returns
        -------
        features : torch.Tensor
            tensor of size (n_tiles, features_dim)
        """
        # intermediate output
        # see https://github.com/facebookresearch/dino/blob/cb711401860da580817918b9167ed73e3eef3dcf/eval_linear.py#L208
        features = self.backbone.get_intermediate_layers(images, n)
        #features = torch.cat([x[:, 0] for x in features], dim=-1)
        if output==True:
            logit=features[n-1]
            return logit
        else:
            return features
    

path='/home/zhangdi/mycode/paper1/models/'
MODEL_WEIGHTS = {
        "iBOTViTBasePANCAN": os.path.join(path,"ibot_vit.pth"),
        }

def base_vit(path_model,device,num_classes):
    #torch.cuda.set_device(device)
    model=vit_base(patch_size=16, num_classes=num_classes, use_mean_pooling=False)
    
    state_dict = torch.load(path_model, map_location="cpu")
    state_dict = state_dict['teacher']
    state_dict = {
            k.replace("module.", ""): v for k, v in state_dict.items()
            }
    state_dict = {
            k.replace("backbone.", ""): v for k, v in state_dict.items()
            }
    model.load_state_dict(state_dict, strict=False)

    return model
def base_vit_nomode(path_model,device,num_classes):
    #torch.cuda.set_device(device)
    model=vit_base(patch_size=16, num_classes=num_classes, use_mean_pooling=False)
    
    state_dict = torch.load(path_model, map_location="cpu")
    #state_dict = state_dict['teacher']
    state_dict = {
            k.replace("module.", ""): v for k, v in state_dict.items()
            }
    state_dict = {
            k.replace("backbone.", ""): v for k, v in state_dict.items()
            }
    model.load_state_dict(state_dict, strict=False)

    return model
'''
if __name__=='__main__':
    pre_network=r'/home/zhangdi/mycode/paper1/models/ibot_vit.pth'
    device = torch.device("cuda:1")
    num_classes=2
    model=base_vit(pre_network,device,num_classes).to(device)
    normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    # 调用模型
    temp_x = torch.rand(1,3,224,224).cuda()
    temp_x = normalize(temp_x)
    features = model(temp_x)
    print(features)'''
def ibotvit(path_model,device):
#if __name__=='__main__':
    
    #device = torch.device("cuda:1")  # GPU 1
    torch.cuda.set_device(device) 
    model=iBOTViT(path=path_model).to(device)

    return model

    '''
    first_param_device = next(model.parameters()).device

    print(f"Model is on {first_param_device}")
    
    path='/home/zhangdi/mycode/paper1/models/ibot_vit_weight.pth'




    weights_path = '/home/zhangdi/mycode/paper1/models/ibot_vit_weight.pth'
    state_dict = torch.load(weights_path, map_location=device)
    teacher_state_dict = state_dict['teacher']
    model.load_state_dict(teacher_state_dict)#, strict=False)'''




    '''
    # 打印权重字典的键名
    print("Keys in the state_dict:")
    for key in state_dict.keys():
        print(key)

    # 如果权重文件包含了不止一个模型（例如 'teacher' 和 'student'），
    # 可能需要先指定要查看的部分
    if 'teacher' in state_dict:
        print("\nKeys in the teacher model:")
        for key in state_dict['teacher'].keys():
            print(key)






    model.load_state_dict(torch.load(path, map_location=device))'''

    '''
    transform = transforms.Compose([
        transforms.Resize((224, 224)),  # 调整图像尺寸
        transforms.ToTensor(),           # 将图像转换为Tensor
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # 标准化
        ])
    normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    # 调用模型
    temp_x = torch.rand(1,3,224,224).cuda()
    temp_x = normalize(temp_x)
    features = model(temp_x,3,output=False)

    # 查看输出特征
    #print(features)

    #最后的输出，实际上增加了一个线性分类器
    #linear_classifier = LinearClassifier(embed_dim, num_labels=args.num_labels)'''